spring.datasource.url=jdbc:oracle:thin:@10.145.1.235:1522:rundb1
spring.datasource.username=HRIS_DEVP
spring.datasource.password=hrisdb@1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.thymeleaf.cache=false
 

server.port=8088
 
#logging.file.name=logs/dnb.log
#logging.level.root=INFO
#logging.level.com.bsp=DEBUG
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level  %msg%n


iam.base-url=http://10.145.15.47:8080/bsp/iam
#iam.base-url=http://localhost:8080
iam.public-key-url=${iam.base-url}/auth/public-key
app.iam.refresh-url=${iam.base-url}/auth/refresh
app.iam.login-url=${iam.base-url}/
app.iam.dashboard-url=${iam.base-url}/auth/dashboard
app.iam.logout-url=${iam.base-url}/logout
# Stipend Procedure
#dnb.stipend.schema=PAY_ADMIN
dnb.stipend.procedure-name=DNBPBILL_PROC
dnb.sap.procedure-name=PAY_ADMIN.CREATE_DNB_TABLES
dnb.proc.monthly-update=PROC_DNB_MASTER_UPDATE

server.servlet.context-path=/DNB


#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n